-- Up Migration
-- Tenant organization (data model 01-platform-org.md; migration order item 1 of the data-model README).
-- Isolation and grants by table class (ADR-0013): tenants is `platform`, all other tables are `tenant`.
-- ids are UUIDv7 generated by the application (ADR-0014 §2): no defaults on id columns.
-- Tenant tables: primary key (tenant_id, ...), references inside a tenant are composite
-- (tenant_id, x_id) -> t (tenant_id, id), so a row can never point to another tenant's row.
-- Grants are explicit; pharmacy_app has no default privileges (Task 2 of the data-layer plan).

-- tenants - network (class platform). Created by the operator; a tenant reads only its own row.
create table pharmacy.tenants (
  id uuid primary key,
  code text not null unique check (code ~ '^[a-z0-9-]{3,32}$'),
  name text not null,
  status text not null default 'active' check (status in ('active', 'blocked')),
  billing_name text,
  billing_tax_id text,
  billing_address text,
  billing_phone text,
  billing_email text,
  billing_bank_details text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- roles - tenant roles (ADR-0018). name is a language map {"ru": ..., "tj": ...} (D6).
create table pharmacy.roles (
  tenant_id uuid not null references pharmacy.tenants (id),
  id uuid not null,
  name jsonb not null check (jsonb_typeof(name) = 'object' and name <> '{}'::jsonb),
  is_owner boolean not null default false,
  status text not null default 'active' check (status in ('active', 'archived')),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, id),
  check (status <> 'archived' or archived_at is not null)
);
-- One owner role per tenant.
create unique index roles_owner_uq on pharmacy.roles (tenant_id) where is_owner;

-- employees - one role per employee (ADR-0018); store scope all / list (employee_stores).
create table pharmacy.employees (
  tenant_id uuid not null references pharmacy.tenants (id),
  id uuid not null,
  role_id uuid not null,
  login text not null,
  full_name text not null,
  employee_code text,
  phone text,
  language text check (language in ('ru', 'tj')),
  store_scope text not null check (store_scope in ('all', 'list')),
  status text not null default 'active' check (status in ('active', 'blocked', 'archived')),
  archived_at timestamptz,
  permissions_version bigint not null default 1 check (permissions_version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, id),
  unique (tenant_id, employee_code),
  foreign key (tenant_id, role_id) references pharmacy.roles (tenant_id, id),
  check (status <> 'archived' or archived_at is not null)
);
create unique index employees_login_uq on pharmacy.employees (tenant_id, lower(login));
create index employees_role_idx on pharmacy.employees (tenant_id, role_id);

-- employee_credentials - password / PIN / one-time code hashes (ADR-0008). Never synchronized.
create table pharmacy.employee_credentials (
  tenant_id uuid not null references pharmacy.tenants (id),
  employee_id uuid not null,
  password_hash text,
  password_pepper_version integer check (password_pepper_version >= 1),
  password_changed_at timestamptz,
  pin_hash text,
  pin_pepper_version integer check (pin_pepper_version >= 1),
  pin_failed_attempts integer not null default 0 check (pin_failed_attempts >= 0),
  pin_locked_at timestamptz,
  one_time_code_hash text,
  one_time_code_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, employee_id),
  foreign key (tenant_id, employee_id) references pharmacy.employees (tenant_id, id),
  -- Every hash carries its pepper version; a one-time code always expires.
  check ((password_hash is null) = (password_pepper_version is null)),
  check ((pin_hash is null) = (pin_pepper_version is null)),
  check ((one_time_code_hash is null) = (one_time_code_expires_at is null))
);

-- role_permissions - permission keys "module:action"; the catalog lives in libs/shared/domain.
create table pharmacy.role_permissions (
  tenant_id uuid not null references pharmacy.tenants (id),
  role_id uuid not null,
  permission text not null check (permission ~ '^[a-z0-9-]+:[a-z0-9-]+$'),
  created_at timestamptz not null default now(),
  primary key (tenant_id, role_id, permission),
  foreign key (tenant_id, role_id) references pharmacy.roles (tenant_id, id)
);

-- tenant_settings - one row per tenant.
create table pharmacy.tenant_settings (
  tenant_id uuid primary key references pharmacy.tenants (id),
  default_language text not null default 'ru' check (default_language in ('ru', 'tj')),
  timezone text not null default 'Asia/Dushanbe',
  return_period_days integer not null default 14 check (return_period_days >= 0),
  cashier_session_idle_min integer not null default 15 check (cashier_session_idle_min > 0),
  pin_min_length integer not null default 4 check (pin_min_length >= 4),
  sync_interval_min integer not null default 15 check (sync_interval_min between 5 and 1440),
  receipt_footer jsonb check (receipt_footer is null or jsonb_typeof(receipt_footer) = 'object'),
  expiry_reminder_days integer not null default 30 check (expiry_reminder_days >= 0),
  supplier_payment_reminder_days integer not null default 3 check (supplier_payment_reminder_days >= 0),
  piece_price_rounding_dirams integer not null default 10 check (piece_price_rounding_dirams >= 1),
  backdating_max_days integer not null default 30 check (backdating_max_days >= 0),
  prescription_retention_days integer not null default 90 check (prescription_retention_days between 1 and 3650),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid,
  foreign key (tenant_id, updated_by) references pharmacy.employees (tenant_id, id)
);
create index tenant_settings_updated_by_idx on pharmacy.tenant_settings (tenant_id, updated_by);

-- legal_entities - legal entities of the network (D5): receipt requisites, 1C export, period closing.
create table pharmacy.legal_entities (
  tenant_id uuid not null references pharmacy.tenants (id),
  id uuid not null,
  name text not null,
  tax_id text not null,
  legal_address text not null,
  phone text,
  email text,
  bank_details text,
  closed_until date,
  closed_until_set_by uuid,
  closed_until_set_at timestamptz,
  status text not null default 'active' check (status in ('active', 'archived')),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, id),
  foreign key (tenant_id, closed_until_set_by) references pharmacy.employees (tenant_id, id),
  check ((closed_until_set_by is null) = (closed_until_set_at is null)),
  check (status <> 'archived' or archived_at is not null)
);
create unique index legal_entities_tax_id_active_uq on pharmacy.legal_entities (tenant_id, tax_id)
  where status = 'active';
create index legal_entities_closed_until_set_by_idx on pharmacy.legal_entities (tenant_id, closed_until_set_by);

-- stores - pharmacy or warehouse. The platform sees the registry without the address and changes mode.
create table pharmacy.stores (
  tenant_id uuid not null references pharmacy.tenants (id),
  id uuid not null,
  legal_entity_id uuid not null,
  name text not null,
  code text not null check (code ~ '^[A-Z0-9]{1,8}$'),
  address text not null,
  kind text not null check (kind in ('pharmacy', 'warehouse')),
  mode text not null default 'online' check (mode in ('online', 'offline_pending', 'offline')),
  status text not null default 'active' check (status in ('active', 'closed')),
  print_receipt_default boolean not null default true,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, id),
  unique (tenant_id, code),
  foreign key (tenant_id, legal_entity_id) references pharmacy.legal_entities (tenant_id, id),
  check (status <> 'closed' or closed_at is not null)
);
create index stores_legal_entity_idx on pharmacy.stores (tenant_id, legal_entity_id);

-- employee_stores - store scope of an employee with store_scope = 'list'.
create table pharmacy.employee_stores (
  tenant_id uuid not null references pharmacy.tenants (id),
  employee_id uuid not null,
  store_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (tenant_id, employee_id, store_id),
  foreign key (tenant_id, employee_id) references pharmacy.employees (tenant_id, id),
  foreign key (tenant_id, store_id) references pharmacy.stores (tenant_id, id)
);
create index employee_stores_store_idx on pharmacy.employee_stores (tenant_id, store_id);

-- terminals - cash registers bound by a device credential (ADR-0008). Revocation is immediate.
create table pharmacy.terminals (
  tenant_id uuid not null references pharmacy.tenants (id),
  id uuid not null,
  store_id uuid not null,
  name text not null,
  credential_hash bytea not null unique check (octet_length(credential_hash) = 32),
  bound_by uuid not null,
  bound_at timestamptz not null,
  last_seen_at timestamptz,
  revoked_at timestamptz,
  revoked_by uuid,
  created_at timestamptz not null default now(),
  primary key (tenant_id, id),
  unique (tenant_id, store_id, name),
  foreign key (tenant_id, store_id) references pharmacy.stores (tenant_id, id),
  foreign key (tenant_id, bound_by) references pharmacy.employees (tenant_id, id),
  foreign key (tenant_id, revoked_by) references pharmacy.employees (tenant_id, id),
  check ((revoked_at is null) = (revoked_by is null))
);
create index terminals_bound_by_idx on pharmacy.terminals (tenant_id, bound_by);
create index terminals_revoked_by_idx on pharmacy.terminals (tenant_id, revoked_by);

-- Row level security: enabled and forced on every table (the owner is not exempt).
alter table pharmacy.tenants enable row level security;
alter table pharmacy.tenants force row level security;
alter table pharmacy.roles enable row level security;
alter table pharmacy.roles force row level security;
alter table pharmacy.employees enable row level security;
alter table pharmacy.employees force row level security;
alter table pharmacy.employee_credentials enable row level security;
alter table pharmacy.employee_credentials force row level security;
alter table pharmacy.role_permissions enable row level security;
alter table pharmacy.role_permissions force row level security;
alter table pharmacy.tenant_settings enable row level security;
alter table pharmacy.tenant_settings force row level security;
alter table pharmacy.legal_entities enable row level security;
alter table pharmacy.legal_entities force row level security;
alter table pharmacy.stores enable row level security;
alter table pharmacy.stores force row level security;
alter table pharmacy.employee_stores enable row level security;
alter table pharmacy.employee_stores force row level security;
alter table pharmacy.terminals enable row level security;
alter table pharmacy.terminals force row level security;

-- tenants: the tenant path reads its own row; the platform path manages the registry (no delete).
create policy tenant_self_read on pharmacy.tenants for select to pharmacy_app
  using (id = (select current_setting('app.tenant_id')::uuid));
create policy platform_all on pharmacy.tenants for all to pharmacy_platform
  using (true) with check (true);
grant select on pharmacy.tenants to pharmacy_app;
grant select, insert, update on pharmacy.tenants to pharmacy_platform;

-- Tenant tables: fail-closed tenant filter (no missing_ok) for pharmacy_app, full DML.
create policy tenant_isolation on pharmacy.roles for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));
create policy tenant_isolation on pharmacy.employees for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));
create policy tenant_isolation on pharmacy.employee_credentials for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));
create policy tenant_isolation on pharmacy.role_permissions for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));
create policy tenant_isolation on pharmacy.tenant_settings for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));
create policy tenant_isolation on pharmacy.legal_entities for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));
create policy tenant_isolation on pharmacy.stores for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));
create policy tenant_isolation on pharmacy.employee_stores for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));
create policy tenant_isolation on pharmacy.terminals for all to pharmacy_app
  using (tenant_id = (select current_setting('app.tenant_id')::uuid))
  with check (tenant_id = (select current_setting('app.tenant_id')::uuid));

grant select, insert, update, delete on
  pharmacy.roles,
  pharmacy.employees,
  pharmacy.employee_credentials,
  pharmacy.role_permissions,
  pharmacy.tenant_settings,
  pharmacy.legal_entities,
  pharmacy.stores,
  pharmacy.employee_stores,
  pharmacy.terminals
to pharmacy_app;

-- stores on the platform path: the registry columns (no address) for all tenants, and mode only.
create policy platform_registry_read on pharmacy.stores for select to pharmacy_platform
  using (true);
create policy platform_store_mode on pharmacy.stores for update to pharmacy_platform
  using (true) with check (true);
grant select (id, tenant_id, name, mode, status, created_at, closed_at) on pharmacy.stores to pharmacy_platform;
grant update (mode) on pharmacy.stores to pharmacy_platform;
