/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EmployeeCredentials {
  createdAt: Generated<Timestamp>;
  employeeId: string;
  oneTimeCodeExpiresAt: Timestamp | null;
  oneTimeCodeHash: string | null;
  passwordChangedAt: Timestamp | null;
  passwordHash: string | null;
  passwordPepperVersion: number | null;
  pinFailedAttempts: Generated<number>;
  pinHash: string | null;
  pinLockedAt: Timestamp | null;
  pinPepperVersion: number | null;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Employees {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  employeeCode: string | null;
  fullName: string;
  id: string;
  language: string | null;
  login: string;
  permissionsVersion: Generated<bigint>;
  phone: string | null;
  roleId: string;
  status: Generated<string>;
  storeScope: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface EmployeeStores {
  createdAt: Generated<Timestamp>;
  employeeId: string;
  storeId: string;
  tenantId: string;
}

export interface LegalEntities {
  archivedAt: Timestamp | null;
  bankDetails: string | null;
  closedUntil: string | null;
  closedUntilSetAt: Timestamp | null;
  closedUntilSetBy: string | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: string;
  legalAddress: string;
  name: string;
  phone: string | null;
  status: Generated<string>;
  taxId: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface RolePermissions {
  createdAt: Generated<Timestamp>;
  permission: string;
  roleId: string;
  tenantId: string;
}

export interface Roles {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: string;
  isOwner: Generated<boolean>;
  name: Json;
  status: Generated<string>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Stores {
  address: string;
  closedAt: Timestamp | null;
  code: string;
  createdAt: Generated<Timestamp>;
  id: string;
  kind: string;
  legalEntityId: string;
  mode: Generated<string>;
  name: string;
  printReceiptDefault: Generated<boolean>;
  status: Generated<string>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Tenants {
  billingAddress: string | null;
  billingBankDetails: string | null;
  billingEmail: string | null;
  billingName: string | null;
  billingPhone: string | null;
  billingTaxId: string | null;
  code: string;
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface TenantSettings {
  backdatingMaxDays: Generated<number>;
  cashierSessionIdleMin: Generated<number>;
  createdAt: Generated<Timestamp>;
  defaultLanguage: Generated<string>;
  expiryReminderDays: Generated<number>;
  piecePriceRoundingDirams: Generated<number>;
  pinMinLength: Generated<number>;
  prescriptionRetentionDays: Generated<number>;
  receiptFooter: Json | null;
  returnPeriodDays: Generated<number>;
  supplierPaymentReminderDays: Generated<number>;
  syncIntervalMin: Generated<number>;
  tenantId: string;
  timezone: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface Terminals {
  boundAt: Timestamp;
  boundBy: string;
  createdAt: Generated<Timestamp>;
  credentialHash: Buffer;
  id: string;
  lastSeenAt: Timestamp | null;
  name: string;
  revokedAt: Timestamp | null;
  revokedBy: string | null;
  storeId: string;
  tenantId: string;
}

export interface DB {
  employeeCredentials: EmployeeCredentials;
  employees: Employees;
  employeeStores: EmployeeStores;
  legalEntities: LegalEntities;
  rolePermissions: RolePermissions;
  roles: Roles;
  stores: Stores;
  tenants: Tenants;
  tenantSettings: TenantSettings;
  terminals: Terminals;
}
