/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  actingOperatorId: string | null;
  action: string;
  businessDate: string;
  correlationId: string;
  details: Generated<Json>;
  employeeId: string | null;
  entityId: string | null;
  entityType: string | null;
  id: string;
  impersonationId: string | null;
  recordedAt: Generated<Timestamp>;
  source: string;
  storeId: string | null;
  tenantId: string;
  terminalId: string | null;
}

export interface Batches {
  costPerPieceDirams: bigint;
  createdAt: Generated<Timestamp>;
  expiryDate: string;
  id: string;
  isStarting: Generated<boolean>;
  lotNumber: string | null;
  origin: string;
  productId: string;
  purchasePricePerPackDirams: bigint;
  sourceDocumentId: string;
  storeId: string;
  supplierId: string | null;
  tenantId: string;
}

export interface Categories {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: string;
  markupBp: number | null;
  name: Json;
  posSortOrder: Generated<number>;
  status: Generated<string>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface DictionaryValues {
  archivedAt: Timestamp | null;
  code: string | null;
  createdAt: Generated<Timestamp>;
  id: string;
  isSystem: Generated<boolean>;
  kind: string;
  name: Json;
  status: Generated<string>;
  tenantId: string;
}

export interface DiscountRules {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: string;
  level: string;
  name: Json;
  status: Generated<string>;
  storeScope: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
  validFrom: string | null;
  validTo: string | null;
}

export interface DiscountRuleStores {
  createdAt: Generated<Timestamp>;
  ruleId: string;
  storeId: string;
  tenantId: string;
}

export interface DiscountRuleTiers {
  createdAt: Generated<Timestamp>;
  minTotalDirams: bigint;
  percentBp: number;
  ruleId: string;
  tenantId: string;
}

export interface DocumentCounters {
  createdAt: Generated<Timestamp>;
  kind: string;
  lastNumber: bigint;
  storeId: string;
  tenantId: string;
  year: number;
}

export interface Documents {
  comment: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  documentDate: string;
  id: string;
  number: string;
  paymentDueDate: string | null;
  postedAt: Timestamp | null;
  postedBy: string | null;
  status: Generated<string>;
  storeId: string;
  supplierId: string | null;
  supplierInvoiceDate: string | null;
  supplierInvoiceNumber: string | null;
  tenantId: string;
  totalDirams: bigint | null;
  type: string;
  unpostedAt: Timestamp | null;
  unpostedBy: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface EmployeeCredentials {
  createdAt: Generated<Timestamp>;
  employeeId: string;
  oneTimeCodeExpiresAt: Timestamp | null;
  oneTimeCodeHash: string | null;
  passwordChangedAt: Timestamp | null;
  passwordHash: string | null;
  passwordPepperVersion: number | null;
  pinFailedAttempts: Generated<number>;
  pinHash: string | null;
  pinLockedAt: Timestamp | null;
  pinPepperVersion: number | null;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Employees {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  employeeCode: string | null;
  fullName: string;
  id: string;
  language: string | null;
  lastLoginAt: Timestamp | null;
  login: string;
  permissionsVersion: Generated<bigint>;
  phone: string | null;
  roleId: string;
  status: Generated<string>;
  storeScope: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface EmployeeStores {
  createdAt: Generated<Timestamp>;
  employeeId: string;
  storeId: string;
  tenantId: string;
}

export interface GoodsReceiptLines {
  batchId: string | null;
  createdAt: Generated<Timestamp>;
  documentId: string;
  expiryDate: string;
  id: string;
  lineNo: number;
  lotNumber: string | null;
  productId: string;
  purchasePricePerPackDirams: bigint;
  qtyPieces: number;
  retailPriceDraftDirams: bigint;
  tenantId: string;
}

export interface LegalEntities {
  archivedAt: Timestamp | null;
  bankDetails: string | null;
  closedUntil: string | null;
  closedUntilSetAt: Timestamp | null;
  closedUntilSetBy: string | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: string;
  legalAddress: string;
  name: string;
  phone: string | null;
  status: Generated<string>;
  taxId: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface OpeningBalanceLines {
  batchId: string | null;
  createdAt: Generated<Timestamp>;
  documentId: string;
  expiryDate: string;
  id: string;
  isStarting: Generated<boolean>;
  lineNo: number;
  lotNumber: string | null;
  productId: string;
  purchasePricePerPackDirams: bigint;
  qtyPieces: number;
  retailPriceDraftDirams: bigint | null;
  supplierId: string | null;
  tenantId: string;
}

export interface OperatorCredentials {
  createdAt: Generated<Timestamp>;
  oneTimeCodeExpiresAt: Timestamp | null;
  oneTimeCodeHash: string | null;
  operatorId: string;
  passwordChangedAt: Timestamp | null;
  passwordHash: string | null;
  passwordPepperVersion: number | null;
  updatedAt: Generated<Timestamp>;
}

export interface Operators {
  createdAt: Generated<Timestamp>;
  fullName: string;
  id: string;
  lastLoginAt: Timestamp | null;
  login: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface PlatformAuditLog {
  action: string;
  actorKind: string;
  correlationId: string;
  details: Generated<Json>;
  entityId: string | null;
  entityType: string | null;
  id: string;
  job: string | null;
  operatorId: string | null;
  recordedAt: Generated<Timestamp>;
  tenantId: string | null;
}

export interface ProductBarcodes {
  barcode: string;
  createdAt: Generated<Timestamp>;
  productId: string;
  tenantId: string;
}

export interface Products {
  archivedAt: Timestamp | null;
  article: string | null;
  categoryId: string;
  country: string | null;
  createdAt: Generated<Timestamp>;
  defaultMinStockPieces: number | null;
  dosage: string | null;
  dosageForm: string | null;
  id: string;
  inn: Json | null;
  isControlled: Generated<boolean>;
  isPrescription: Generated<boolean>;
  isPriceRegulated: Generated<boolean>;
  manufacturer: string | null;
  markupBp: number | null;
  maxRetailPricePerPackDirams: bigint | null;
  name: Json;
  piecesPerPack: Generated<number>;
  soldByPiece: Generated<boolean>;
  status: Generated<string>;
  tenantId: string;
  unit: string;
  updatedAt: Generated<Timestamp>;
}

export interface RolePermissions {
  createdAt: Generated<Timestamp>;
  permission: string;
  roleId: string;
  tenantId: string;
}

export interface Roles {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: string;
  isOwner: Generated<boolean>;
  name: Json;
  status: Generated<string>;
  templateKey: string | null;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  absoluteExpiresAt: Timestamp;
  authenticatedAt: Timestamp;
  authMethod: string;
  createdAt: Generated<Timestamp>;
  currentStoreId: string | null;
  employeeId: string;
  idleExpiresAt: Timestamp;
  idleTtlSeconds: number;
  jti: string;
  locale: string;
  permissions: Generated<string[]>;
  permissionsVersion: bigint;
  storeScope: Json;
  tenantId: string;
  terminalCredentialHash: string | null;
  terminalId: string | null;
}

export interface StockMovements {
  batchId: string;
  businessDate: string;
  id: string;
  kind: string;
  origin: Generated<string>;
  qtyDeltaPieces: number;
  recordedAt: Generated<Timestamp>;
  reversesMovementId: string | null;
  sourceId: string;
  sourceLineId: string | null;
  sourceType: string;
  storeId: string;
  tenantId: string;
}

export interface StoreProducts {
  createdAt: Generated<Timestamp>;
  priceChangedAt: Timestamp | null;
  priceChangedBy: string | null;
  priceSource: Generated<string>;
  priceVersion: Generated<number>;
  productId: string;
  retailPricePerPackDirams: bigint | null;
  retailPricePerPieceDirams: bigint | null;
  storeId: string;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Stores {
  address: string;
  closedAt: Timestamp | null;
  code: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idempotencyKey: string | null;
  kind: string;
  legalEntityId: string;
  mode: Generated<string>;
  name: string;
  printReceiptDefault: Generated<boolean>;
  status: Generated<string>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface SupplierLedgerEntries {
  amountDirams: bigint;
  businessDate: string;
  dueDate: string | null;
  id: string;
  kind: string;
  legalEntityId: string;
  recordedAt: Generated<Timestamp>;
  recordedBy: string;
  sourceId: string;
  sourceType: string;
  supplierId: string;
  tenantId: string;
}

export interface Suppliers {
  address: string | null;
  archivedAt: Timestamp | null;
  bankDetails: string | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: string;
  name: string;
  paymentTermDays: Generated<number>;
  phone: string | null;
  status: Generated<string>;
  taxId: string | null;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Tenants {
  billingAddress: string | null;
  billingBankDetails: string | null;
  billingEmail: string | null;
  billingName: string | null;
  billingPhone: string | null;
  billingTaxId: string | null;
  blockedAt: Timestamp | null;
  blockedBy: string | null;
  blockReason: string | null;
  city: Generated<string>;
  code: string;
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  ownerEmail: string | null;
  ownerFullName: string | null;
  ownerLogin: string | null;
  ownerPhone: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface TenantSettings {
  backdatingMaxDays: Generated<number>;
  cashierSessionIdleMin: Generated<number>;
  createdAt: Generated<Timestamp>;
  defaultLanguage: Generated<string>;
  expiryReminderDays: Generated<number>;
  piecePriceRoundingDirams: Generated<number>;
  pinMinLength: Generated<number>;
  prescriptionRetentionDays: Generated<number>;
  receiptFooter: Json | null;
  returnPeriodDays: Generated<number>;
  supplierPaymentReminderDays: Generated<number>;
  syncIntervalMin: Generated<number>;
  tenantId: string;
  timezone: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface Terminals {
  boundAt: Timestamp;
  boundBy: string;
  createdAt: Generated<Timestamp>;
  credentialHash: Buffer;
  id: string;
  lastSeenAt: Timestamp | null;
  name: string;
  revokedAt: Timestamp | null;
  revokedBy: string | null;
  storeId: string;
  tenantId: string;
}

export interface DB {
  auditLog: AuditLog;
  batches: Batches;
  categories: Categories;
  dictionaryValues: DictionaryValues;
  discountRules: DiscountRules;
  discountRuleStores: DiscountRuleStores;
  discountRuleTiers: DiscountRuleTiers;
  documentCounters: DocumentCounters;
  documents: Documents;
  employeeCredentials: EmployeeCredentials;
  employees: Employees;
  employeeStores: EmployeeStores;
  goodsReceiptLines: GoodsReceiptLines;
  legalEntities: LegalEntities;
  openingBalanceLines: OpeningBalanceLines;
  operatorCredentials: OperatorCredentials;
  operators: Operators;
  platformAuditLog: PlatformAuditLog;
  productBarcodes: ProductBarcodes;
  products: Products;
  rolePermissions: RolePermissions;
  roles: Roles;
  sessions: Sessions;
  stockMovements: StockMovements;
  storeProducts: StoreProducts;
  stores: Stores;
  supplierLedgerEntries: SupplierLedgerEntries;
  suppliers: Suppliers;
  tenants: Tenants;
  tenantSettings: TenantSettings;
  terminals: Terminals;
}
