import type { InvoiceListFilter } from '@pharmacy/shared-dto';
import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { apiRequest } from '@/shared/api';

export const billingKeys = {
  all: ['billing'] as const,
  summary: (period: string) => ['billing', 'summary', period] as const,
  invoices: (query: {
    filter?: InvoiceListFilter;
    limit?: number;
    offset?: number;
  }) => ['billing', 'invoices', query] as const,
  invoice: (id: string) => ['billing', 'invoice', id] as const,
  payments: (query: { limit?: number; offset?: number }) =>
    ['billing', 'payments', query] as const,
};

export function useInvoices(query: {
  filter?: InvoiceListFilter;
  limit?: number;
  offset?: number;
}) {
  return useQuery({
    queryKey: billingKeys.invoices(query),
    queryFn: ({ signal }) => apiRequest('invoices.list', { query, signal }),
    placeholderData: keepPreviousData,
  });
}

/** PDF of an invoice, generated by apps/api; downloaded with the operator's cookie session. */
export function invoicePdfHref(id: string): string {
  return `/api/v1/platform/invoices/${encodeURIComponent(id)}/pdf`;
}
