/**
 * Identifiers generated by the application (ADR-0015, ось 6в): UUIDv7 (RFC 9562) — time-ordered
 * primary keys and the Idempotency-Key of buffered POS operations. One function for apps/api and
 * the frontends; the generator is the `uuid` package, not a home-grown implementation.
 */
import { v7 } from 'uuid';

export function uuidv7(): string {
  return v7();
}
