import baseConfig from '../../eslint.config.mjs';

export default [
  ...baseConfig,
  // Generated by `nx run api:db-types` (kysely-codegen); never hand-edited.
  { ignores: ['src/core/database/db.generated.ts'] },
];
