import baseConfig from '../../eslint.config.mjs';

export default [
  ...baseConfig,
  // Generated by `nx run api:db-types` (kysely-codegen); never hand-edited.
  { ignores: ['src/core/database/db.generated.ts'] },
  // Data-access boundaries (ADR-0013 §7, ADR-0006); mirrored by test/architecture.ts.
  {
    files: ['src/**/*.ts'],
    ignores: [
      'src/core/database/**',
      'src/app/platform/**',
      'src/app/sync/**',
      'src/**/*.spec.ts',
      'src/**/*.int-spec.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'pg',
              message:
                'ADR-0006: use TenantDatabase from core/database; no direct pg access.',
            },
          ],
          patterns: [
            {
              group: [
                '**/core/database/platform',
                '**/core/database/platform/*',
              ],
              message:
                'ADR-0013: PlatformDatabase is available only in app/platform/** and app/sync/**.',
            },
            {
              group: ['**/core/database/*', '!**/core/database/index'],
              message: 'ADR-0006: import core/database through its index.',
            },
          ],
        },
      ],
    },
  },
];
